sudo: required
language: csharp
dist: trusty
mono: none

os:
  - linux

branches:  
  only:
    - master

services:
  - docker

after_script:
  - docker images
before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
  provider: script
  script: docker build -t igromanru/switch-lan-party-server:latest . && docker push igromanru/switch-lan-party-server
  skip_cleanup: true
  on:
    branch: master