sudo: required
language: csharp
dist: trusty
mono: none

os:
  - linux

branches:  
  only:
    - master

services:
  - docker

before_script:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

script:
  - docker build -t igromanru/switch-lan-party-server:latest .

deploy:
  provider: script
  script: docker push igromanru/switch-lan-party-server
  skip_cleanup: true
  on:
    branch: master